### ISSUE TITLE
Add showKeyboard and hideKeyboard methods

### ISSUE THREAD

**Issue by mori-honest** [milosmns/silly-android#4]
protected void showKeyboard() {

            InputMethodManager inputMethodManager = (InputMethodManager) activity.getSystemService(Context.INPUT_METHOD_SERVICE);
            if (activity.getCurrentFocus() == null) {
                inputMethodManager.toggleSoftInput(InputMethodManager.SHOW_FORCED,0);
            } else {
                View view = activity.getCurrentFocus();
                inputMethodManager.showSoftInput(view,InputMethodManager.SHOW_FORCED);
            }
        }

        /**
         * Hide keyboard.
         */
        protected void hideKeyboard() {

            InputMethodManager inputMethodManager = (InputMethodManager) activity.getSystemService(Context.INPUT_METHOD_SERVICE);
            View view = activity.getCurrentFocus();
            if (view == null) {
                if (inputMethodManager.isAcceptingText())
                    inputMethodManager.toggleSoftInput(InputMethodManager.HIDE_NOT_ALWAYS, 0);
            } else {
                if (view instanceof EditText)
                    ((EditText) view).setText(((EditText) view).getText().toString()); // reset edit text bug on some keyboards bug
                inputMethodManager.hideSoftInputFromInputMethod(view.getWindowToken(), InputMethodManager.HIDE_NOT_ALWAYS);
            }          
        }

**Comment by mori-honest** [comment]
the methods which i pasted here are not tested
so make sure you test them before using them

**Comment by milosmns** [comment]
Released v1.1: https://github.com/milosmns/silly-android/releases/tag/v1.1

I added a couple of things related to keyboards (plus open/close detection), but there is no easy/proper/non-crashing way to show the keyboard except for requesting focus from an edit text - so I didn't include the `showKeyboard()` method at all. Hide is available.
